version: "3"
services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
    environment:
      - JEKYLL_UID=1000
      - JEKYLL_GID=1000
      - DEBUG=true
      - FULL_CHOWN=true